### ISSUE TITLE
Why self.first_pass = True in Scaler method

### ISSUE THREAD

**Issue by haoliuhl** [pat-coady/trpo#13]
Hello, in utils.py [29 line](https://github.com/pat-coady/trpo/blob/master/src/utils.py#L29), there is `self.first_pass = True`, as far as what I know, this will not lead to a running mean method, isn't it? Plz point out what I misunderstood, thanks.

**Comment by Erichliu00** [comment]
my wrong.

**Comment by haoliuhl** [comment]
my wrong, sorry.
