### ISSUE TITLE
DOI for citation

### ISSUE THREAD

**Issue by mkoseoglu** [pat-coady/trpo#16]
Thank you very much for your code and blog post! It was super helpful. 

I think you do not have a paper for your code. Have you thought of getting a DOI for your code repository so that people can cite it formally? 

https://guides.github.com/activities/citable-code/

**Comment by pat-coady** [comment]
Good idea, I will do that.

**Comment by pat-coady** [comment]
Done:

@misc{patrick_coady_2018_1183378,
  author       = {Patrick Coady},
  title        = {pat-coady/trpo: First release.},
  month        = feb,
  year         = 2018,
  doi          = {10.5281/zenodo.1183378},
  url          = {https://doi.org/10.5281/zenodo.1183378}
}

**Comment by gvgramazio** [comment]
> Done:
> 
> @misc{patrick_coady_2018_1183378,
> author = {Patrick Coady},
> title = {pat-coady/trpo: First release.},
> month = feb,
> year = 2018,
> doi = {10.5281/zenodo.1183378},
> url = {[https://doi.org/10.5281/zenodo.1183378}](https://doi.org/10.5281/zenodo.1183378%7D)
> }

Why don't you add it in the README?
