### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by gautam1858** [pat-coady/trpo#20]
Hi I am getting the following error

`raise error.DeprecatedEnv('Env {} not found (valid versions include {})'.format(id, matching_envs))
gym.error.DeprecatedEnv: Env Reacher-v1 not found (valid versions include ['Reacher-v2'])
`
Can you please help me solve this problem

**Comment by gautam1858** [comment]
need to make reacher-v2 for higher version of gym

**Comment by pat-coady** [comment]
Sorry, catching up on e-mail. It looks like you figured out the problem?

Let me know if you still need a hand.
