### ISSUE TITLE
Does this code use TRPO?

### ISSUE THREAD

**Issue by ghost** [pat-coady/trpo#24]
The folder says TRPO but the description includes PPO. If this repository runs PPO and not TRPO then the repository should be renamed to PPO.

**Comment by ryanmaxwell96** [comment]
Did you ever come to a concensus as to which algorithm is actually being used? It seems to me that TRPO is indeed being used based on the other function names but I was a little confused on this as well.

**Comment by Lukeeeeee** [comment]
> Did you ever come to a concensus as to which algorithm is actually being used? It seems to me that TRPO is indeed being used based on the other function names but I was a little confused on this as well.

PPO it is.
