### ISSUE TITLE
Unusual replay buffer

### ISSUE THREAD

**Issue by ghost** [pat-coady/trpo#27]
In your replay buffer you are recording states and value functions {s,V}. Shouldn't the replay buffer record the states, actions, rewards, next states {s,a,r,s'} instead?

**Comment by pat-coady** [comment]
Hi @ImranRolo - busy end-of-year push at work. I will look at this, but will be about a week. Sorry, Pat.

**Comment by pat-coady** [comment]
A year later ... the replay buffer is only used to train the value function. Soe only states and values are required.

**Comment by pat-coady** [comment]
See above comment.
