### ISSUE TITLE
able to run FetchPickAndPlace-v1 ?

### ISSUE THREAD

**Issue by MrDadaGuy** [pat-coady/trpo#28]
Trying to get some of the Openai gym Robotics environments working.  I've added the appropriate imports so it pulls in FetchPickAndPlace-v1 but the script fails on this line

    obs_dim = env.observation_space.shape[0]

I've had a look and shape is None -- although observation_space looks like this:

Dict(achieved_goal:Box(3,), desired_goal:Box(3,), observation:Box(25,))

any ideas how I could modify the code to get past this?

Thanks!

**Comment by MrDadaGuy** [comment]
I've hacked basic support for OpenAI Gym Robotics in my fork...

https://github.com/MrDadaGuy/trpo

I'm running FetchPickAndPlace-v1 now

**Comment by pat-coady** [comment]
I've migrated the repo over to PyBullet (and TensorFlow2). I don't have a MuJoCo license any more, so am unable to test test `FetchPickAndPlace-v1`. I fixed some things related to the way action and observation shapes were handled. Hopefully this resolves the problem with that env.
