### ISSUE TITLE
How much  episodes should we do ? 

### ISSUE THREAD

**Issue by wenyijiang** [pat-coady/trpo#3]
Hi!
    Thanks for sharing the code！
    I trian the Humanoid .
    I have a question ,how much episodes should I do? When the episodes is much than 20000 , the human can not walk better.

**Comment by pat-coady** [comment]
The performance starts to get reasonable at 40k episodes, here is the training curve:
https://gist.github.com/pat-coady/e313cae7e8bcb6c2679917d09338fba1

Aside from being a complex task, I think the humanoid environment is a little flawed. It has 377 observation dimensions, but many of them contain no information. But my implementation just scales the first layer of the neural net to 10x the observation dimension. This gives an overly large NN. So, another option is to hand edit hid1_size to be something like 450 in the policy.py file.

Hope this helps.
