### ISSUE TITLE
Is there information on what actions and observations really are?

### ISSUE THREAD

**Issue by wenyijiang** [pat-coady/trpo#4]
Hi!
Is there information on what actions and observations really are?
 I can't seem to find if there is any info on what actions and observation arrays that are supplied really are?
For example , the humanoid ,what the 17 and 376 represented for ? the  joint angles or joint velocities ?
I look for the  docs and cannot find the answer . How can I figure this out?
Thanks a lot !

**Comment by pat-coady** [comment]
Sorry, I don't know the answer. The xml files here may help:

https://github.com/openai/gym/tree/master/gym/envs/mujoco/assets

For the humanoid, it seems most of the observations are meaningless (or at least seem to be zero most of the time). The "roboschool" humanoid has 17 actions, but only 45 observations.

Hope this helps.
