### ISSUE TITLE
Can't work on CartPole-v1

### ISSUE THREAD

**Issue by AlexZhou1995** [pat-coady/trpo#8]
Hi,

I only changed a few codes to make this project work on CartPole-v1 env, but the result was not good.
The mean reward is always about 9.3 and can't goes up.

Do you have tested the performance on some easy environments?

Thank you

**Comment by pat-coady** [comment]
I think CartPole-v1 is a discrete control environment. This implementation
is for continuous control tasks.

On testing, yes, I posted results from environments with 1-dim control to
17-dim control

Hope this helps.
